### ISSUE TITLE
Checking for if chd was not created with createdvd?

### ISSUE THREAD

**Issue by hrydgard** [rtissera/libchdr#107]
People are starting to use the new CHD support in PPSSPP, and are complaining about bad performance.

It turns out that CHDs created with `createcd` or `createraw` are very slow to access with PSP-sized sector accesses.

How can I detect such CHDs and warn the user or reject them through the API? I guess chd_getheader, but what fields should I check?

Just check hunkbytes == 2048?

**Comment by rtissera** [comment]
_createcd_ is really a bad idea for DVD / UMD yeah.
DVD support is WIP (also need to add the newly released zstd support with MAME/chdman 0.262)
What's the PSP-sized sector accesses typical length ?
If my memories are correct UMD is similar to DVD aka MODE1/2048

Yes, checking hunkbytes or unitbytes in the header is probably the straightest way to address this.
Haven't touched the project for a while and need to remember.

LZMA decompression is the big performance cost here, createraw shall not give issues if UMD is compressed with small number of sectors (4 to 8 looks like a good compromise).
Also the upcoming support for zstd will totally change potential performance issues, however it will require to be explicitely required when calling chdman, not very user friendly.

**Comment by hrydgard** [comment]
On the PSP, sectors are always 2048 bytes, aligned to 0 (no odd-sized header). Which is nice and consistent, and like DVD there are no icky audio tracks. So I'll check for that, at least.

beta or not, with `createdvd` things work smoothly.

What do you mean "small number of sectors, 4 to 8"? do individual sectors get grouped into bigger units for compression? What field do I look at for that, if so?

**Comment by rtissera** [comment]
Yes with createraw you can specify how many sectors are grouped
A unit being a sector
A hunk being a group of sectors, then passed to the compression codec

Le mer. 31 janv. 2024 à 20:40, Henrik Rydgård ***@***.***> a
écrit :

**Comment by hrydgard** [comment]
For PSP, it's a very bad idea to anything bigger than individual sectors. We don't perform any caching on top of the compressed ISO, so if a game reads a lot of consecutive sectors one by one (which is common), well, badness ensues.

So, the createdvd default of individual 2048 byte sectors is by far the best, and I'm now throwing this in the user's face if the hunk size isn't 2048:

![image](https://github.com/rtissera/libchdr/assets/130929/cbe58857-5a48-4ab8-849b-2dc5621cafff)

**Comment by rtissera** [comment]
Agreed.
I will add the DVD metadata tag to the list and it should be good to go.
chdman does compress sector per sector for dvd media so it should fit perfectly.
Of course, users need to be educated to use the createdvd command.
I know by experience many of them use some bash / batch files drag and dropping files or folders on them.

**Comment by hrydgard** [comment]
ok. Well, checking for 2048 works for me for now as-is, so you can close this if you like.
