### ISSUE TITLE
Shared object fails to build

### ISSUE THREAD

**Issue by Sanaki** [rtissera/libchdr#14]
I fixed this locally by adding `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` to CMakeLists.txt, but I'm not familiar enough with cmake to be certain that would have no drawbacks.

```
[ 98%] Linking C static library libchdr-static.a
[100%] Linking C shared library libchdr-shared.so
[100%] Built target chdr-static
/usr/bin/ld: libflac-static.a(stream_decoder.c.o): relocation R_X86_64_PC32 against symbol `FLAC__STREAM_METADATA_APPLICATION_ID_LEN' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/chdr-shared.dir/build.make:202: recipe for target 'libchdr-shared.so' failed
make[2]: *** [libchdr-shared.so] Error 1
CMakeFiles/Makefile2:221: recipe for target 'CMakeFiles/chdr-shared.dir/all' failed
make[1]: *** [CMakeFiles/chdr-shared.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by rtissera** [comment]
It does enable -fPIC which is the right way to fix it.
Please submit a PR (setting this flag only when building a shared library), and I will merge it.

**Comment by Sanaki** [comment]
This is a outside my realm of expertise by a fair margin, but I've poked at this a bit and am not entirely happy with the results (at least as far as my understanding is concerned). Since it's the deps in need of enabling pic, short of compiling them twice I'm not yet clear on the best approach. Thus far the best solution I have is adding it only to zlib, lzma, and flac, but while that leaves libchdr static unmodified from the current build, those static deps will be changed, and I'm getting the impression that isn't preferable. I'll keep poking at it later on and see what I can come up with. If nothing else, this is an opportunity to learn.

Current method (can be added at the end of CMakeLists.txt):
```cmake
set_property(TARGET flac-static PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET lzma-static PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET zlibstatic PROPERTY POSITION_INDEPENDENT_CODE ON)
```

**Comment by rtissera** [comment]
Can you try again with latest code (merged a pull request tonight) ?

**Comment by Sanaki** [comment]
Using the standard method (`cmake .. && make` from within build directory), no luck just yet.

```make
/usr/bin/ld: liblzma-static.a(LzmaDec.c.o): relocation R_X86_64_PC32 against symbol `LzmaDec_InitDicAndState' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/chdr-shared.dir/build.make:202: recipe for target 'libchdr-shared.so' failed
make[2]: *** [libchdr-shared.so] Error 1
```

**Comment by realnc** [comment]
> Using the standard method (`cmake .. && make` from within build directory), no luck just yet.

Don't do that. Use this instead:

    cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON ../

**Comment by Sanaki** [comment]
Duly noted. Builds fine with those flags. I probably should get more familiar with cmake, considering how often I'm forced to interact with it.

**Comment by rtissera** [comment]
Should be fixed by @realnc PR I just merged.
