### ISSUE TITLE
libchdr no longer compiles with MSVC

### ISSUE THREAD

**Issue by LukeUsher** [rtissera/libchdr#25]
The ssize_t type is undefined when using Visual Studio 2019.

This can be fixed by defining it in coretypes.h or similar as follows:
```c++
#ifdef _WIN32
#ifdef _MSC_VER
typedef size_t ssize_t;
#endif
#endif
```

**Comment by rtissera** [comment]
Hello, thanks for the report.
Can you make a pull request ?
