### ISSUE TITLE
Suggestions for v6 - ZStandard Codec Support

### ISSUE THREAD

**Issue by kcgen** [rtissera/libchdr#35]
**ZStandard Codec Support**
- Likely supported via LibZStandard
- Pass-through of API settings for common ZStandard features such as: number of cores, block sizes, compression settings, and so on.
- The API will allow emulator-specific and platform-specific settings to optimize the performance of of the library.

**Comment by Sanaki** [comment]
This repo is a library for reading MAME's chd format. It doesn't have any influence over the chd format itself. For that, you'll need to open issues on https://github.com/mamedev/mame/.

**Comment by kcgen** [comment]
Thanks @Sanaki! (Closing)

**Comment by Sanaki** [comment]
I'd imagine this applies to #34 and #36 as well.

**Comment by kcgen** [comment]
(Ref: https://github.com/mamedev/mame/issues/7386)

**Comment by InquisitiveCoder** [comment]
Can this be revisited? MAME just added zstd support to chdman in this PR: https://github.com/mamedev/mame/pull/11827

**Comment by rtissera** [comment]
Owww that’s a HUGE win !
Yes definitely !

Le lun. 11 déc. 2023 à 20:41, InquisitiveCoder ***@***.***> a
écrit :

**Comment by malvarenga123** [comment]
Should this issue be reopened until it's implemented?

**Comment by rtissera** [comment]
Yes since MAME chaman now does it.

**Comment by Sanaki** [comment]
I believe this was resolved in #106 and can be closed again.

**Comment by rtissera** [comment]
Yes, indeed, MAME team bit the bullet and implemented in chdman 0.262
It needs to be manually specified at compression time.
Closing.
