### ISSUE TITLE
Visual Studio project file?

### ISSUE THREAD

**Issue by whocares0101** [rtissera/libchdr#39]
Add VS project files so a static/dynamic library can easily be created.
This would make adding this to other projects easier.

**Comment by rtissera** [comment]
Tou can generate such files using CMake

Le sam. 7 nov. 2020 à 02:03, whocares0101 <notifications@github.com> a
écrit :

**Comment by whocares0101** [comment]
Nice but maybe add some build instructions somewhere so it's easier to build this for beginners.

So I used `cmake -G "Visual Studio 16 2019" -A x64` but it does not compile with VS2019

Fisrt error is `#define CHD_EXPORT __attribute__ ((visibility("default")))` in `chd.h`
this should be changed to sometinhg like this
```
#ifdef _MSC_VER
    #define CHD_EXPORT __declspec(dllexport)
#else
    #define CHD_EXPORT __attribute__ ((visibility("default")))
#endif
```

Then it can't find `zlib.h` so I had to add `$(SolutionDir)deps\zlib-1.2.11` to the include path.

Now ssize_t is not defined, adding this `typedef size_t ssize_t;` to the above ifdef fixes this.

Seems to compile now, maybe this could be improved so it just works?
