### ISSUE TITLE
Loading CHD files >2GiB?

### ISSUE THREAD

**Issue by whocares0101** [rtissera/libchdr#40]
I can't seem to load CHD files larger than 2GiB, all I get is `CHDERR_DECOMPRESSION_ERROR`, I used cmake and VS2019 x64 build.
Everything compiles fine and loading smaller CHD files seems to work.

**Comment by whocares0101** [comment]
The problem seems to be in `coretypes.h`, `fseek` and `ftell` are only good for 32 bit.
I don't know what the best solution is for this but I switched to `_fseeki64` and `_ftelli64` also updated `core_fsize` to use 64 bit types and now it seems to work.

Large file support in C++
https://stackoverflow.com/q/965725/14044248

**Comment by rtissera** [comment]
Good catch can you submit a PR ?
Good job on PCSX2 integration !

**Comment by kcgen** [comment]
> Good job on PCSX2 integration !

.. and DOSBox-X integration !

**Comment by CookiePLMonster** [comment]
Hey @whocares0101, are you going to submit a PR addressing this?

**Comment by rtissera** [comment]
Closed by 443319766523e6396abe52a8e1721146e3943896
