### ISSUE TITLE
libchdr shared library

### ISSUE THREAD

**Issue by orbea** [rtissera/libchdr#7]
Would it be possible that it could be made so that a libchdr shared library could be built so it can be installed system wide? My main interest is that I would be able to reuse it in downstream projects instead of requiring libchdr to be built statically. This would greatly help in comparing upstream libchdr with downstream implementations.

Additionally it would also be nice to be able to build libchdr with system version of libraries like flac. At least with flac, a system version works fine with libchdr in RetroArch.

**Comment by rtissera** [comment]
Well there's no reason not to.
I will look into this and community submitted fixes I need to merge.

**Comment by orbea** [comment]
Thanks! My familiarity with cmake is limited and I'm not sure I can implement this in a good way soon.

**Comment by rtissera** [comment]
Fixed in latest commit.
