### ISSUE TITLE
Adding it to HPS1x64 and HPS2x64

### ISSUE THREAD

**Issue by Zero3K** [rtissera/libchdr#75]
How would one go about doing it to add CHD support to them?

**Comment by Zero3K** [comment]
Well?

**Comment by rtissera** [comment]
Had a look at your source tree. Looks doable, you should only have to add libchdr as a git submodule and add two classes for CHD similar to CDImage / DVDImage.

**Comment by Zero3K** [comment]
Does that involve lots of code to write?

**Comment by Zero3K** [comment]
Anyone want to make a PR in its repo in order to get it supported by it?

**Comment by Zero3K** [comment]
What about adding code to CDImage and DVDImage that has it recognize the .chd image?

**Comment by Zero3K** [comment]
It is now being used by HPS1x64 and HPS2x64 since 12/09/2023. So, I am now closing this issue.
